version: '3.8'

services:
  wordpress:
    image: wordpress:6.5
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          memory: 2G

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 2G

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - frontend
      - backend

  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NETDATA_CLAIM_TOKEN=etI3r4VLfiDaRoOQ8ultss78sd8kcRvUEpcnbMJrIU4S8iSRb8lvUDOY3Yygm4M-d9nMvTEvELEmdQwHOtaorEpwcdvVLTIASnN9qsoE7cgYHGsMPSizxK950H0F39zKekEcLDw
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=4a3b53b6-46f5-4d6a-a645-3cb5921dd3dd
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

volumes:
  wordpress-data:
  db-data:
  netdataconfig:
  netdatalib:
  netdatacache:
