---
services:
  sql-primary01:
    container_name: sql-primary01
    restart: unless-stopped
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=password1234
      - MARIADB_USER=wp
      - MARIADB_PASSWORD=wppass
      - MARIADB_DATABASE=wordpress
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=replicapass
    volumes:
      - ./sql-primary01:/var/lib/mysql
      - ./primary01.cnf:/etc/mysql/conf.d/custom.cnf

  sql-primary02:
    container_name: sql-primary02
    restart: unless-stopped
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=password1234
      - MARIADB_USER=wp
      - MARIADB_PASSWORD=wppass
      - MARIADB_DATABASE=wordpress
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=replicapass
    volumes:
      - ./sql-primary02:/var/lib/mysql
      - ./primary02.cnf:/etc/mysql/conf.d/custom.cnf

  wp:
    container_name: wp
    restart: unless-stopped
    image: wordpress:6-php8.1-apache
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: sql-primary01
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
