---
- name: Deploy root ssh keys
  ansible.posix.authorized_key:
    user: root
    key: "{{ item.ssh_key }}"
    state: "{{ item.state }}"
    exclusive: false
  with_items:
    - "{{ users }}"
  when:
    - item.name is defined
    - item.state == 'present'
