---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
    component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      component: agent
  template:
    metadata:
      labels:
        app: zabbix
        component: agent
    spec:
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent2:latest
          env:
            - name: ZBX_HOSTNAME
              value: "Zabbix server"
            - name: ZBX_PASSIVE_ALLOW
              value: "false"
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
spec:
  ports:
    - port: 10050
      targetPort: 10050
  selector:
    app: zabbix
    component: agent
