---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      component: server
  template:
    metadata:
      labels:
        app: zabbix
        component: server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:latest
          env:
            - name: DB_SERVER_HOST
              value: zabbix-mysql
            - name: DB_SERVER_PORT
              value: "3306"
            - name: MYSQL_USER
              value: zabbix
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: zabbix
          ports:
            - containerPort: 10051
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
spec:
  type: NodePort
  ports:
    - port: 10051
      targetPort: 10051
      nodePort: 30051
  selector:
    app: zabbix
    component: server
