---
# tasks file for deploy_swarm_service

#- name: Import volume
#  ansible.builtin.copy:
#    src: docker_wordpress_data/_data/
#    dest: wordpress_data/
#    owner: www-data
#    group: www-data

- name: Create Docker volume
  ansible.builtin.file:
    path: ./wordpress_data
    state: directory
    owner: www-data
    group: www-data

- name: Template Docker Compose file
  ansible.builtin.template:
    src: custom-apache2.conf.j2
    dest: custom-apache2.conf

- name: Template Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: docker-compose.yml

- name: Deploy Docker stack
  ansible.builtin.command:
    cmd: docker stack deploy -c docker-compose.yml my_stack
