---
services:
  sql-primary:
    container_name: sql-primary
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_USER: wp
      MARIADB_PASSWORD: wppass
      MARIADB_REPLICATION_USER: replication_user
      MARIADB_REPLICATION_PASSWORD: replicapass
      MARIADB_DATABASE: wordpress
    volumes:
      - ./primary.conf:/etc/mysql/conf.d/custom.cnf
    networks:
      - wpnet

  sql-replica01:
    container_name: sql-replica01
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_REPLICATION_USER: replication_user
      MARIADB_REPLICATION_PASSWORD: replicapass
      MARIADB_MASTER_HOST: sql-primary
    volumes:
      - ./replica01.conf:/etc/mysql/conf.d/custom.cnf
    networks:
      - wpnet

  sql-replica02:
    container_name: sql-replica02
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_REPLICATION_USER: replication_user
      MARIADB_REPLICATION_PASSWORD: replicapass
      MARIADB_MASTER_HOST: sql-primary
    volumes:
      - ./replica02.conf:/etc/mysql/conf.d/custom.cnf
    networks:
      - wpnet

  wp:
    container_name: wp
    image: wordpress:php8.3-apache
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: sql-primary
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - wpnet
    depends_on:
      - sql-primary

networks:
  wpnet:

volumes:
  wordpress:
  db:
