# ================== general variables ===================
VM_environment: "kvm" # can be azure, kvm // azure is not supported for all functionalities yet.
# switch generation of ssh key to false if you already have one
generate_ssh_key: true
path_to_public_key: .ssh/rsa_key_ansible_kvm.pub
path_to_private_key: .ssh/rsa_key_ansible_kvm
vm_net: default
cleanup_tmp: True
host_key_checking: False

# ================== infrastructure level ===================
location_iso_debian: https://debian.osuosl.org/debian/dists/stable/main/installer-amd64/
hosts_group: default_hosts_group

### SWARM SPECIFICS
user_vm_swarm: swarm
name_vm_swarm: swarm_machine
vcpu_vm_swarm: 1
memory_vm_swarm: 1024
password_vm_swarm: default_swarm_password
swarm_rootpass: default_swarm_rootpass
disk_size_vm_swarm: 3G
### needed for use all features of netdata
netdata_claim_token:
netdata_claim_url:
netdata_claim_rooms:
