---
services:
  mariadb-primary:
    image: mariadb:11.2
    container_name: mariadb-primary
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - mariadb
    volumes:
      - mariadb-primary:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mariadb:

volumes:
  mariadb-primary:
