services:
  sql-primary01:
    build: .
    container_name: sql-primary01
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb.conf.d1:/etc/mysql/conf.d
      - ./replication-setup1.sql:/docker-entrypoint-initdb.d/replication-setup.sql
    networks:
      - mariadbnet

  sql-primary02:
    build: .
    container_name: sql-primary02
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb.conf.d2:/etc/mysql/conf.d
      - ./replication-setup2.sql:/docker-entrypoint-initdb.d/replication-setup.sql
    networks:
      - mariadbnet

networks:
  mariadbnet:
    driver: bridge
