---
services:
  nginx:
    image: nginx:1.27
    container_name: web-server
    ports:
      - 80:80
      - 443:443
    networks:
      - external_network
      - front_network
    depends_on:
      - mariadb
    volumes:
      - ./nginx/mynginx.conf:/etc/nginx/conf.d/mynginx.conf:ro

  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    networks:
      - back_network
    volumes:
      - /srv/my-app/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE: database
      MARIADB_USER: "user1"
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_root_password

  wordpress:
    image: wordpress:6.6.1
    container_name: wordpress_service
    restart: always
    ports:
      - 8900:80
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
    secrets:
      - wordpress_db_password
    networks:
      - front_network
      - back_network
    volumes:
      - /srv/my-app/wordpress:/var/www/html
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: pma_service
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD_FILE: /run/secrets/pma_password
    secrets:
      - pma_password
    ports:
      - 8080:80
    depends_on:
      - mariadb
    networks:
      - front_network
      - back_network

networks:
  external_network:
  front_network:
    internal: true
  back_network:
    internal: true

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  pma_password:
    file: ./secrets/pma_password.txt
  wordpress_db_password:
    file: ./secrets/wordpress_db_password.txt
