---
- name: Converge
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=300
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: "sshd"
