global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "mariadb-primary01"
    static_configs:
      - targets: ["mysqld-exporter1:9104"]

  - job_name: "mariadb-primary02"
    static_configs:
      - targets: ["mysqld-exporter2:9104"]
