version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wordpress-network

  wordpress:
    build: .
    container_name: wordpress-container
    ports:
      - "8080:80"
    volumes:
      - apache-data:/var/www/html
    depends_on:
      - db
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - wordpress-network

volumes:
  apache-data:
  mysql-data:

networks:
  wordpress-network:
    driver: bridge
