services:
  wordpress:
    image: wordpress:6.6.1-php8.3-apache
    container_name: wordpress_wpApp
    # restart: always
    ports:
      - 0.0.0.0:8080:80
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app:/var/www/html
    networks:
      - front
      - back

  mariadb:
    image: mariadb:11.4
    container_name: mariadb_wpApp
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - back

  adminer:
    image: adminer:4.8.1
    container_name: adminer_wpApp
    # restart: always
    ports:
      - 127.0.0.1:8081:8080
    depends_on:
      - mariadb
    networks:
      - back
      - front
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: mariadb

  # zabbix:
  #   image: zabbix/zabbix-appliance:alpine-6.0.0
  #   container_name: zabbix_wpApp
  #   # restart: always
  # networks:
  #   - monitoring
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    secrets:
      - netdata_claim_token
      - netdata_claim_url
      - netdata_claim_rooms
    environment:
      - NETDATA_CLAIM_TOKEN_FILE=/run/secrets/netdata_claim_token
      - NETDATA_CLAIM_URL_FILE=/run/secrets/netdata_claim_url
      - NETDATA_CLAIM_ROOMS_FILE=/run/secrets/netdata_claim_rooms
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

secrets:
  netdata_claim_token:
    file: ./secrets.yml
    name: NETDATA_CLAIM_TOKEN
  netdata_claim_url:
    file: ./secrets.yml
    name: NETDATA_CLAIM_URL
  netdata_claim_rooms:
    file: ./secrets.yml
    name: NETDATA_CLAIM_ROOMS
    
networks:
  front:
  back:
    internal: true
  monitoring:

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
