version: '3.8'

services:
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
      - "3306:3306"
    volumes:
      - web_data:/var/www/html
    networks:
      - webnet

volumes:
  web_data:

networks:
  webnet:
    driver: bridge
