---
# tasks file for configure_node_manager

- name: Init a new swarm with default parameters
  community.docker.docker_swarm:
    state: present

- name: Get Swarm Manager Token
  command: docker swarm join-token -q manager
  register: manager_token

- name: Get IP of the new VM
  shell: hostname -I | awk '{print $1}'
  register: output_ip_address

- name: Check if the host is already in the inventory
  ansible.builtin.shell: 'grep "{{ ansible_hostname }}" {{ inventory_file }}'
  register: grep_result
  ignore_errors: yes
  failed_when: grep_result.rc != 0 and grep_result.rc != 1
  delegate_to: localhost

- name: Ensure [all:vars] section exists in the inventory file
  ansible.builtin.lineinfile:
    path: ./hosts
    line: "[all:vars]"
    create: yes
    insertafter: EOF
  delegate_to: localhost

- name: Replace or add the manager_token in [all:vars]
  ansible.builtin.lineinfile:
    path: ./hosts
    regexp: "^manager_token="
    line: "manager_token={{ manager_token.stdout }}"
    insertafter: '^\[all:vars\]$'
    create: yes
  delegate_to: localhost

- name: Replace or add the manager_node_ip in [all:vars]
  ansible.builtin.lineinfile:
    path: ./hosts
    regexp: "^manager_node_ip="
    line: "manager_node_ip={{ output_ip_address.stdout }}"
    insertafter: '^\[all:vars\]$'
    create: yes
  delegate_to: localhost
