---
- name: SSH-keygen remove ip from known host
  ansible.builtin.shell: ssh-keygen -f "/home/{{ ansible_user }}/.ssh/known_hosts" -R "{{ hostvars[vm_name]['ansible_host'] }}"
  become: true
  become_user: "{{ ansible_user }}"
  become_method: sudo
  ignore_errors: true
- name: Détruire les snapshots de la VM si elle existe
  shell: |
    for snap in $(virsh snapshot-list --name "{{ vm_name }}"); do
      virsh snapshot-delete --domain "{{ vm_name }}" "$snap"
    done
  ignore_errors: true
  register: snapshot_delete_results
  changed_when: snapshot_delete_results.rc == 0

- name: Détruire la VM si elle existe
  community.libvirt.virt:
    command: destroy
    name: "{{ vm_name }}"
  ignore_errors: true

- name: Undefine the VM if it exists
  community.libvirt.virt:
    command: undefine
    name: "{{ vm_name }}"
    force: true
  ignore_errors: true

- name: Supprimer le disque de la VM
  file:
    path: /var/lib/libvirt/images/{{ vm_name }}.qcow2
    state: absent
