- name: Install middleware
  hosts: "{{ vm_name }}"
  vars_files:
    - group_vars/secret.yml
  vars:
    ansible_user: "{{ user_vm_swarm }}"
    arch_mapping: # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  roles:
    - install_docker
