---

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: helenedocker
      WORDPRESS_DB_PASSWORD: test
      WORDPRESS_DB_NAME: dockerDB
    ports:
      - "9000:80"
    volumes:
      - apache-data:/usr/local/apache2/htdocs   # persistant volume for Apache
    networks:
      - helnetwork

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: helenedocker
      PMA_PASSWORD: test
    depends_on:
      - mariadb # To make sure this container starts before phpmyadmin
    ports:
      - "8081:80"
    networks:
      - helnetwork

  mariadb:
    image: mariadb:11.5.1-ubi9-rc
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dockerDB
      MYSQL_USER: helenedocker
      MYSQL_PASSWORD: test
    volumes:
      - /srv/mariadb:/var/lib/mysql # persistant volume for MariadB
    networks:
      - helnetwork

  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/host/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NETDATA_CLAIM_TOKEN=Uifb9AJgYTIBXjJVZ7mf4PDIvMvMp0y_hllAUdTSWScsFcDLlNOJsZBml1NvjPsMNlQeyrxjaDFf_f8mo4In_DQcZHP82kJbOpvbOc5xnAQmi6rRIw1UB9NkadbV1UoNoAhu24U
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=da483e65-d808-4605-a3da-8e8a876bb5e1


volumes:
  apache-data:
  mysql-data:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  helnetwork:
