services:

  mariadb:
    container_name: mydb
    image: mariadb:11.4
    restart: unless-stopped
    volumes:
      - /srv/docker/mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: toto
      MARIADB_DATABASE: wpdb
      MARIADB_USER: xav
      MARIADB_PASSWORD: titi
    networks:
      - wp-network

  wordpress:
    container_name: mywp
    image: wordpress:6.6
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: xav
      WORDPRESS_DB_PASSWORD: titi
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - /srv/docker/wordpress:/var/www/html
    networks:
      - wp-network

  phpMyAdmin:
    container_name: mypma
    image: phpmyadmin:5.2
    restart: unless-stopped
    ports:
      - 8085:80
    environment:
      PMA_HOST: mydb
      MYSQL_ROOT_PASSWORD: toto
    networks:
      - wp-network


networks:
  wp-network:
